export const CATEGORIES = [
  { slug: 'chargers', name: 'Chargers', tagline: 'Smart power, redefined.', desc: 'Adaptive charging engineered for the next decade of devices.' },
  { slug: 'fast-chargers', name: 'Fast Chargers', tagline: '0 to 80% in minutes.', desc: 'GaN-powered ultra-fast charging at premium thermal efficiency.' },
  { slug: 'cables', name: 'Cables', tagline: 'Bandwidth without compromise.', desc: 'Braided, signal-tuned cables for true 240W delivery.' },
  { slug: 'earbuds', name: 'Earbuds', tagline: 'Sound, intelligently shaped.', desc: 'AI-tuned spatial audio with adaptive noise architecture.' },
  { slug: 'headphones', name: 'Headphones', tagline: 'Cinematic, on you.', desc: 'Studio-grade drivers calibrated by neural acoustics.' },
  { slug: 'speakers', name: 'Speakers', tagline: 'A room, transformed.', desc: 'Self-mapping speakers that learn your space.' },
  { slug: 'smart-devices', name: 'Smart Devices', tagline: 'The ambient layer.', desc: 'Quiet intelligence woven into your everyday environment.' },
  { slug: 'ai-wearables', name: 'AI Wearables', tagline: 'Worn intelligence.', desc: 'Always-on co-pilots for your body, mind and motion.' },
  { slug: 'ai-accessories', name: 'AI Accessories', tagline: 'Beyond accessories.', desc: 'Companions for a more intelligent life.' },
  { slug: 'future-products', name: 'Future Products', tagline: 'Classified.', desc: 'Unannounced. Unreleased. Unforgettable.' },
];

export const PRODUCTS = [
  {
    slug: 'visthar-ai-earbuds',
    name: 'Visthar AI Earbuds',
    category: 'earbuds',
    tagline: 'Spatial audio. Adaptive intelligence.',
    price: 9999,
    status: 'Pre-Book',
    badge: 'CONFIDENTIAL PROTOTYPE',
    image: 'https://images.unsplash.com/photo-1520186994231-6ea0019d8d51?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2OTV8MHwxfHNlYXJjaHwyfHx3aXJlbGVzcyUyMGVhcmJ1ZHMlMjBkYXJrfGVufDB8fHxibGFja3wxNzc4NDQwMzA2fDA&ixlib=rb-4.1.0&q=85',
    features: ['AI Adaptive Noise Architecture', 'Spatial Audio with Head-Tracking', '12mm Bio-Cellulose Drivers', 'Real-time Translation', '36hr Total Battery', 'Wireless + Magnetic Charging'],
    specs: { 'Driver': '12mm Bio-Cellulose', 'Codec': 'LDAC, aptX Lossless', 'ANC': 'AI Adaptive (-42dB)', 'Battery': '8h + 28h case', 'Weight': '4.6g per bud', 'Water': 'IP57' },
  },
  {
    slug: 'visthar-smart-glasses',
    name: 'Visthar AI Smart Glasses',
    category: 'ai-wearables',
    tagline: 'See the world, intelligently.',
    price: 39999,
    status: 'Early Access',
    badge: 'PREVIEW LOCKED',
    image: 'https://images.unsplash.com/photo-1552305608-a69fc8595989?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2ODl8MHwxfHNlYXJjaHwyfHxzbWFydCUyMGdsYXNzZXMlMjBmdXR1cmlzdGljfGVufDB8fHxibGFja3wxNzc4NDQwMzA2fDA&ixlib=rb-4.1.0&q=85',
    features: ['Live Audio Descriptions for Vision Accessibility', 'Real-time Object & Text Recognition', 'Whisper Bone-Conduction Audio', 'On-device LLM', 'Magnetic Prescription Lenses', '14hr Active Battery'],
    specs: { 'Display': 'MicroLED 1080p per eye', 'Compute': 'Visthar V1 Neural Chip', 'Camera': '12MP cinematic', 'Mic': '5-array beamforming', 'Weight': '38g', 'Connectivity': 'BT 5.4, Wi-Fi 7' },
  },
  {
    slug: 'visthar-neon-speaker',
    name: 'Visthar Neon Speaker',
    category: 'speakers',
    tagline: 'A room, transformed.',
    price: 14999,
    status: 'Launching Soon',
    badge: 'EARLY ACCESS PRODUCT',
    image: 'https://images.unsplash.com/photo-1617722694908-9be1092d1bc2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NDh8MHwxfHNlYXJjaHwyfHxzbWFydCUyMHNwZWFrZXJ8ZW58MHx8fGJsYWNrfDE3Nzg0NDAzMTR8MA&ixlib=rb-4.1.0&q=85',
    features: ['Room-mapping AI acoustics', '360° immersive sound', 'Reactive neon halo', 'Voice + gesture control', 'Multi-room sync', 'Recycled aluminum chassis'],
    specs: { 'Power': '120W RMS', 'Drivers': '2 x 4" + 1 tweeter', 'Range': '40Hz - 22kHz', 'Wireless': 'Wi-Fi 6E, BT 5.3', 'Mic': 'far-field 6-array', 'Material': '60% recycled Al' },
  },
  {
    slug: 'visthar-pulse-headphones',
    name: 'Visthar Pulse Headphones',
    category: 'headphones',
    tagline: 'Cinematic, on you.',
    price: 24999,
    status: 'Launching Soon',
    badge: 'LAUNCHING SOON',
    image: 'https://images.unsplash.com/photo-1505739718967-6df30ff369c7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2MzR8MHwxfHNlYXJjaHwxfHxwcmVtaXVtJTIwaGVhZHBob25lc3xlbnwwfHx8YmxhY2t8MTc3ODQ0MDMwN3ww&ixlib=rb-4.1.0&q=85',
    features: ['40mm Planar Magnetic drivers', 'Studio-grade ANC', 'Spatial Audio Pro', '60hr battery life', 'Memory-foam protein leather', 'Lossless USB-C audio'],
    specs: { 'Driver': '40mm Planar Magnetic', 'Impedance': '32Ω', 'Battery': '60h ANC on', 'Codec': 'LDAC, LHDC 5.0', 'Weight': '280g', 'Charging': 'USB-C 10min = 8h' },
  },
  {
    slug: 'visthar-magnetic-charger',
    name: 'Visthar Magnetic Charger',
    category: 'fast-chargers',
    tagline: '100W, silently delivered.',
    price: 4999,
    status: 'Pre-Book',
    badge: 'EARLY ACCESS PRODUCT',
    image: 'https://images.unsplash.com/photo-1615526675159-e248c3021d3f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2OTV8MHwxfHNlYXJjaHwxfHx3aXJlbGVzcyUyMGNoYXJnZXJ8ZW58MHx8fGJsYWNrfDE3Nzg0NDAzMTR8MA&ixlib=rb-4.1.0&q=85',
    features: ['100W magnetic alignment', 'Adaptive thermal AI', '3-device simultaneous', 'GaN III silicon', 'Premium ceramic top', 'Carbon-neutral packaging'],
    specs: { 'Power': '100W max', 'Standards': 'Qi2, PPS, PD 3.1', 'Devices': '3 simultaneous', 'Cooling': 'Active VC', 'Material': 'Aerospace Al + ceramic', 'Efficiency': '94%' },
  },
  {
    slug: 'visthar-pulse-band',
    name: 'Visthar Pulse Band',
    category: 'ai-wearables',
    tagline: 'Worn intelligence.',
    price: 12999,
    status: 'Pre-Book',
    badge: 'CONFIDENTIAL PROTOTYPE',
    image: 'https://images.unsplash.com/photo-1647668771036-f692bbdc9f0d?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODB8MHwxfHNlYXJjaHwzfHxzbWFydHdhdGNoJTIwd2VhcmFibGV8ZW58MHx8fGJsYWNrfDE3Nzg0NDAzMTV8MA&ixlib=rb-4.1.0&q=85',
    features: ['AI health co-pilot', 'Continuous biomarker tracking', 'Sleep architecture analysis', 'Stress + recovery AI', '21-day battery', 'Titanium chassis'],
    specs: { 'Sensors': 'PPG, ECG, SpO2, Skin Temp', 'Display': '1.9" AMOLED LTPO', 'Battery': '21 days', 'Water': '10 ATM', 'Connectivity': 'BT 5.4, NFC', 'Material': 'Grade 5 Titanium' },
  },
  {
    slug: 'visthar-air-pro',
    name: 'Visthar Air Pro',
    category: 'earbuds',
    tagline: 'Open-ear, AI-tuned.',
    price: 11999,
    status: 'Launching Soon',
    badge: 'LAUNCHING SOON',
    image: 'https://images.unsplash.com/photo-1520186994231-6ea0019d8d51?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2OTV8MHwxfHNlYXJjaHwyfHx3aXJlbGVzcyUyMGVhcmJ1ZHMlMjBkYXJrfGVufDB8fHxibGFja3wxNzc4NDQwMzA2fDA&ixlib=rb-4.1.0&q=85',
    features: ['Open-ear sport design', 'Adaptive transparency mode', 'Sweat + dust resistant', '10mm titanium drivers', '32hr battery total', 'Beam-forming mics'],
    specs: { 'Driver': '10mm Titanium', 'Codec': 'aptX Adaptive, AAC', 'ANC': 'Transparency only', 'Battery': '8h + 24h case', 'Weight': '5.2g per bud', 'Water': 'IP67' },
  },
  {
    slug: 'visthar-studio-headphones',
    name: 'Visthar Studio',
    category: 'headphones',
    tagline: 'Reference monitoring, untethered.',
    price: 34999,
    status: 'Pre-Book',
    badge: 'CONFIDENTIAL PROTOTYPE',
    image: 'https://images.unsplash.com/photo-1505739718967-6df30ff369c7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2MzR8MHwxfHNlYXJjaHwxfHxwcmVtaXVtJTIwaGVhZHBob25lc3xlbnwwfHx8YmxhY2t8MTc3ODQ0MDMwN3ww&ixlib=rb-4.1.0&q=85',
    features: ['50mm beryllium drivers', 'Studio-grade ANC -48dB', 'Hi-Res Audio certified', '72hr battery with ANC off', 'Hybrid pads (memory foam + protein)', 'Detachable balanced cable'],
    specs: { 'Driver': '50mm Beryllium', 'Impedance': '24\u03a9', 'Battery': '72h ANC off', 'Codec': 'LDAC, aptX HD', 'Weight': '298g', 'Charging': 'USB-C PD' },
  },
  {
    slug: 'visthar-mini-speaker',
    name: 'Visthar Mini',
    category: 'speakers',
    tagline: 'Pocket cinema.',
    price: 6999,
    status: 'Launching Soon',
    badge: 'EARLY ACCESS PRODUCT',
    image: 'https://images.unsplash.com/photo-1617722694908-9be1092d1bc2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NDh8MHwxfHNlYXJjaHwyfHxzbWFydCUyMHNwZWFrZXJ8ZW58MHx8fGJsYWNrfDE3Nzg0NDAzMTR8MA&ixlib=rb-4.1.0&q=85',
    features: ['360\u00b0 sound', '24hr battery', 'IP67 rugged', 'Magnetic stacking', 'Voice assistant', 'Recycled aluminum'],
    specs: { 'Power': '20W RMS', 'Drivers': '2 x full-range', 'Battery': '24h', 'Water': 'IP67', 'Wireless': 'BT 5.3', 'Weight': '420g' },
  },
  {
    slug: 'visthar-gan-charger-65',
    name: 'Visthar GaN 65W',
    category: 'chargers',
    tagline: 'A laptop charger, finally elegant.',
    price: 2999,
    status: 'Pre-Book',
    badge: 'EARLY ACCESS PRODUCT',
    image: 'https://images.unsplash.com/photo-1615526675159-e248c3021d3f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2OTV8MHwxfHNlYXJjaHwxfHx3aXJlbGVzcyUyMGNoYXJnZXJ8ZW58MHx8fGJsYWNrfDE3Nzg0NDAzMTR8MA&ixlib=rb-4.1.0&q=85',
    features: ['65W GaN III silicon', 'Universal voltage', 'Foldable prongs', 'Dual USB-C + USB-A', 'PPS + PD 3.1', '94% efficiency'],
    specs: { 'Power': '65W max', 'Ports': '2x USB-C, 1x USB-A', 'Voltage': '100-240V', 'Material': 'Recycled polycarbonate', 'Size': '52 \u00d7 52 \u00d7 32mm', 'Weight': '120g' },
  },
  {
    slug: 'visthar-braided-cable',
    name: 'Visthar Pro Cable 240W',
    category: 'cables',
    tagline: '240W. USB4. Forever.',
    price: 1499,
    status: 'Launching Soon',
    badge: 'LAUNCHING SOON',
    image: 'https://images.unsplash.com/photo-1616133321649-d29ebc595799?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1NzZ8MHwxfHNlYXJjaHwzfHxkYXJrJTIwdGVjaCUyMGFic3RyYWN0fGVufDB8fHxibGFja3wxNzc4NDQwMzA4fDA&ixlib=rb-4.1.0&q=85',
    features: ['240W EPR delivery', 'USB4 40Gbps', 'Aramid-braided jacket', 'Lifetime warranty', 'Liquid-silicone strain relief', 'E-marker chip'],
    specs: { 'Power': '240W EPR', 'Data': 'USB4 40Gbps', 'Length': '1.2m / 2m', 'Bend life': '50,000 cycles', 'Material': 'Aramid + TPE', 'Warranty': 'Lifetime' },
  },
  {
    slug: 'visthar-pro-glasses',
    name: 'Visthar Smart Glasses Pro',
    category: 'ai-wearables',
    tagline: 'See more. Hear more. Know more.',
    price: 54999,
    status: 'Early Access',
    badge: 'PREVIEW LOCKED',
    image: 'https://images.unsplash.com/photo-1552305608-a69fc8595989?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2ODl8MHwxfHNlYXJjaHwyfHxzbWFydCUyMGdsYXNzZXMlMjBmdXR1cmlzdGljfGVufDB8fHxibGFja3wxNzc4NDQwMzA2fDA&ixlib=rb-4.1.0&q=85',
    features: ['4K MicroLED per eye', 'Eye tracking + gesture nav', 'Always-on AI assistant', 'Live language translation', 'Visual accessibility suite', '20hr battery'],
    specs: { 'Display': 'MicroLED 4K per eye', 'Compute': 'Visthar V2 Neural', 'Camera': '48MP cinematic', 'Mic': '7-array beamforming', 'Weight': '42g', 'Connectivity': 'BT 5.4, Wi-Fi 7, 5G' },
  },
];

export const HERO_BG = 'https://images.unsplash.com/photo-1616133321649-d29ebc595799?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1NzZ8MHwxfHNlYXJjaHwzfHxkYXJrJTIwdGVjaCUyMGFic3RyYWN0fGVufDB8fHxibGFja3wxNzc4NDQwMzA4fDA&ixlib=rb-4.1.0&q=85';
export const ECO_BG = 'https://images.unsplash.com/photo-1712203929597-fc545d291c4c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2MzR8MHwxfHNlYXJjaHwyfHxkYXJrJTIwbGVhdmVzJTIwbmF0dXJlfGVufDB8fHxibGFja3wxNzc4NDQwMzIyfDA&ixlib=rb-4.1.0&q=85';

export const getProduct = (slug) => PRODUCTS.find(p => p.slug === slug);
export const getProductsByCategory = (cat) => PRODUCTS.filter(p => p.category === cat);
export const getCategory = (slug) => CATEGORIES.find(c => c.slug === slug);
